# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2.1.1
      with:
        go-version: 1.14

    # Runs a single command using the runners shell
    - name: Build go2docker executable
      run: |
        go get ./...
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o go2docker

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        title: "Release Build"
        files: |
          go2docker
        
